version: '3'

services:
  web-store-mongo:
    container_name: web-store-mongo
    build:
      context: .
      dockerfile: web-store-mongo.dockerfile
    ports:
      - "27018:27017"

  user-service-mysql:
    container_name: user-service-mysql
    build:
      context: .
      dockerfile: user-service.dockerfile
    ports:
      - "3307:3306"

  order-service-mysql:
    container_name: order-service-mysql
    build:
      context: .
      dockerfile: order-service.dockerfile
    ports:
      - "3308:3306"
            

